title: "Insights Canada"
header-img: "img/map_clusters_hi_caption.jpg"
email: "learn@insightscanada.com"
url: "http://insightscanada.org/"
description: "Insights Canada -- Mathematical sciences talent helping business find solutions. Insights Canada is a collaborative effort led by Canada's mathematical and statistical sciences institutes."
author: "James Colliander"

include: ['_pages']
permalink: /:title/

relative_permalinks: false

#gems: ['jekyll-less']

assets:
  sources:
   - _assets/fonts
   - _assets/js
   - _assets/css
