title: "Insights Canada"
header-img: "img/map_clusters_hi_caption.jpg"
email: "learn@insightscanada.com"
url: "http://insightscanada.org/"

include: ['_pages']
permalink: /:title/

relative_permalinks: false

#gems: ['jekyll-less']

assets:
  sources:
   - _assets/fonts
   - _assets/js
   - _assets/css
