title: 
  en: "Solutions Canada"
  fr: "Solutions Canada"
header-img: "img/map_clusters_hi_caption.jpg"
email: "contact@solutionscanada.com"
url: "http://solutionscanada.com/"
description: 
  en: "Solutions Canada -- Mathematical sciences talent helping business find solutions. Solutions Canada is a collaborative effort led by Canada's mathematical and statistical sciences institutes."
  fr: "Solutions Canada -- Le talent des sciences mathématiques aide les entreprises à trouver des solutions. Solutions Canada est un collaboration mené par les instituts des sciences mathématiques et statistiques du Canada."
index:
  en:
  fr: accueil
author: "James Colliander"
exclude: ['publish.sh', 'ROADMAP.txt']

include: ['_pages']
permalink: /:title/

markdown: kramdown
kramdown:
  input: GFM
  hard-wrap: false

relative_permalinks: false

assets:
  sources:
   - _assets/fonts
   - _assets/js
   - _assets/css

t:
  nav:
    en:
      - name: 'About'
        url: '#about'
      - name: 'Partners'
        url: '#partners'
      - name: 'Funding'
        url: '#funding'
      - name: 'Success Stories'
        url: '/success/'
      - name: 'Contact'
        url: '#contact'
    fr:
      - name: 'Qui sommes-nous?'
        url: '#about'
      - name: 'Partenaires'
        url: '#partners'
      - name: 'Financement'
        url: '#funding'
      - name: 'Histoires de cas'
        url: '/histoires-de-cas/'
      - name: 'Contactez-nous'
        url: '#contact'
  form:
    description:
      en: "Is your business ready for eureka?"
      fr: "Votre entreprise est-elle prête pour eureka?"
    name:
      en: "Your name"
      fr: "Votre nom"
    email:
      en: "Your email"
      fr: "Votre courriel"
    message:
      en: "Your message"
      fr: "Votre message"
    submit:
      en: "Send"
      fr: "Soumettre"
  partners:
    header:
      en: "Your solution partners"
      fr: "Vos partenaires pour les solutions"
    description:
      en: "The five institutes"
      fr: "Les cinq instituts blah blah blah"
  funding:
    header:
      en: "Your funding partners"
      fr: "Vos partenaires pour le financement"
  solutions:
    description:
      en: "Find Solutions"
      fr: "Trouver des solutions"
  contact:
    description:
      en: "Ready to explore a collaboration? Give us a call or send us an email and we will get back to you as soon as possible."
      fr: "Êtes-vous prêts à parler de collaboration?  Appelez-nous ou envoyez-nous un courriel et nous communiquerons avec vous dès que possible."
    header:
      en: "Let's Connect!"
      fr: "Faites-nous signe!"
  about:
    heading:
      en: "Analytics, Optimization, Algorithms"
      fr: "Des spécialistes en analyses avancées, optimisation et algorithmes"
    description:
      en: "Launched by the mathematical and statistical sciences institutes, Solutions Canada matches businesses with scientists and students in research universities to solve problems."
      fr: "Lancé par les instituts de sciences mathématiques et statistiques, Solutions Canada permet aux entreprises de trouver des chercheurs et des étudiants universitaires qui les aideront à résoudre leurs problèmes."
    button:
      en: "Let's connect!"
      fr: "Faites-nous signe!"
