title: 
  en: "Solutions Canada"
  fr: "Solutions Canada"
header-img: "img/map_clusters_hi_caption_brite.jpg"
email: "contact@solutionscanada.com"
url: "http://solutionscanada.com/"
description: 
  en: "Solutions Canada -- Mathematical sciences talent helping business find solutions. Solutions Canada is a collaborative effort led by Canada's mathematical and statistical sciences institutes."
  fr: "Solutions Canada -- Le talent des sciences mathématiques aide les entreprises à trouver des solutions. Solutions Canada est un collaboration mené par les instituts des sciences mathématiques et statistiques du Canada."
index:
  en:
  fr: accueil
author: "James Colliander"
exclude: ['publish.sh', 'ROADMAP.txt']
version: 0.0.2

include: ['_pages']
permalink: /:title/

markdown: kramdown
kramdown:
  input: GFM
  hard-wrap: false

relative_permalinks: false

assets:
  sources:
   - _assets/fonts
   - _assets/js
   - _assets/css

t:
  nav:
    en:
      - name: 'About'
        url: '#about'
#      - name: 'Partners'
#        url: '#partners'
#      - name: 'Funding'
#        url: '#funding'
      - name: 'Success Stories'
        url: '/success/'
      - name: 'Contact'
        url: '#contact'
    fr:
      - name: 'Qui sommes-nous?'
        url: '#about'
#      - name: 'Partenaires'
#        url: '#partners'
#     - name: 'Financement'
#        url: '#funding'
      - name: 'Histoires de cas'
        url: '/histoires-de-cas/'
      - name: 'Contactez-nous'
        url: '#contact'
  introduction:
    header:
      en: "Is your business ready for eureka?"
      fr: "Votre entreprise est-elle prête pour eurêka?"
    description:
      en: "
          Solutions Canada matches businesses and their researchers to outstanding
          mathematicians, statisticians, computer scientists, and their students at universities 
          across the country.
          We reach out to businesses and non-profits that seek expertise in the quantitative 
          sciences to advance the success of their organization's operations. 
          Solutions Canada is a joint venture of  five mathematical and statistical sciences 
          institutes in Canada. The mission of these institutes is 
          to promote research, training and collaboration in the mathematical and statistical sciences, 
          including applications for industrial innovation. 
          "
      fr: "
          Solutions Canada s'efforce de
          mobiliser les mathématiciens, les statisticiens, les informaticiens et
          leurs étudiants pour qu'ils s'attaquent aux défis des entreprises.
          Nous visons à aider les entreprises qui ont
          besoin d'une expertise en sciences quantitatives pour faire réussir leurs
          activités. 
          Solutions Canada est un projet conjoint des cinq instituts de sciences
          mathématiques et statistiques du Canada. La mission de ces instituts est de promouvoir la recherche, la
          formation et la collaboration en sciences mathématiques et statistiques, y
          compris les applications industrielles. 
          "
    button:
      en: "Let's connect!"
      fr: "Faites-nous signe!"
  form:
    description:
      en: "Is your business ready for eureka?"
      fr: "Votre entreprise est-elle prête pour eurêka?"
    name:
      en: "Your name"
      fr: "Votre nom"
    email:
      en: "Your email"
      fr: "Votre courriel"
    message:
      en: "Your message"
      fr: "Votre message"
    submit:
      en: "Send"
      fr: "Soumettre"
  partners:
    header:
      en: "Your solution partners"
      fr: "Vos partenaires pour les solutions"
    description:
      en: "
          Solutions Canada is a joint venture of the five mathematical and statistical sciences 
          institutes in Canada, reaching out to businesses requiring expertise in the quantitative 
          sciences to advance the success of their operations. The mission of these institutes is 
          to promote research, training and collaboration in the mathematical and statistical sciences, 
          including applications for industrial innovation. 
          Solutions Canada  matches businesses with research challenges to outstanding 
          mathematicians, statisticians, computer scientists, and their students at universities 
          across the country.
          "
      fr: "Solutions Canada est un projet conjoint des cinq instituts de sciences
          mathématiques et statistiques du Canada, visant les entreprises qui ont
          besoin d'une expertise en sciences quantitatives pour faire réussir leurs
          activités. La mission de ces instituts est de promouvoir la recherche, la
          formation et la collaboration en sciences mathématiques et statistiques, y
          compris les applications industrielles. Solutions Canada s'efforce de
          mobiliser les mathématiciens, les statisticiens, les informaticiens et
          leurs étudiants pour qu'ils s'attaquent aux défis des entreprises."
  funding:
    header:
      en: "Your funding partners"
      fr: "Vos partenaires pour le financement"
  solutions:
    description:
      en: "Find Solutions"
      fr: "Trouver des solutions"
  contact:
    header:
      en: "Let's Connect!"
      fr: "Faites-nous signe!"
    description:
      en: "Ready to explore a collaboration? Tell us who you are, tell us about your company, 
      and the research problems you need to address. Solutions Canada will get back to you with some ideas and
      possible research contacts."
      fr: "Prêt à explorer une collaboration? Dites-nous qui vous êtes, ce que fait votre entreprise, et quels sont les
          problèmes de recherche qui se posent dans celle-ci. Solutions Canada vous
          fournira quelques pistes de solutions et des contacts universitaires."
    description2:
      en: "Or click below to send us an email about your company and its interests."
      fr: "Ou cliquez ci-dessous pour nous envoyer un courriel concernant votre entreprise et ses intérêts."
  about:
    heading:
      en: "Analytics, Optimization, Algorithms"
      fr: "Des spécialistes en analyses avancées, optimisation et algorithmes"
    description:
      en: "Launched by the mathematical and statistical sciences institutes, Solutions Canada matches businesses with scientists and students in research universities to solve problems."
      fr: "Lancé par les instituts de sciences mathématiques et statistiques, Solutions Canada permet aux entreprises de trouver des chercheurs et des étudiants universitaires qui les aideront à résoudre leurs problèmes."
    button:
      en: "Let's connect!"
      fr: "Faites-nous signe!"
  success:
    heading:
      en: "SUCCESS STORIES"
      fr: "HISTORIES DE CAS"
